### ISSUE TITLE
Why not LANL mdtest

### ISSUE THREAD

**Issue by johnbent** [glennklockwood/mdtest-apex#1]
Hey Glenn,

Why did you create your own mdtest?  Why not use the LANL one?
https://github.com/MDTEST-LANL/mdtest

Is there a problem with the LANL one?

Thanks,

John

**Comment by glennklockwood** [comment]
This was supposed to be a meta-repo that contained the necessary docs to build the mdtest benchmark tarball that was provided to APEX bidders as part of the N9-Crossroads procurement process.  At the time I didn't know that LANL was maintaining a copy of mdtest on github, so I couldn't just submodule it like I did for https://github.com/glennklockwood/ior-apex.

That said, since the APEX bidding process is over, this repo is defunct.  I'll probably throw it out and use LANL-mdtest for the next APEX benchmark suite.

**Comment by johnbent** [comment]
Thanks Glenn.

I'm being a bit of a busybody since I don't own the LANL mdtest github repo
but I am interested in getting the community to converge on just one single
one.  A LANL guy just merged their mdtest into their IOR.  Which is great
because it strips all the garbage #ifdef/#else crap out of mdtest in favor
of using the much nicer IOR function pointer table.  That should be pushed
soon to the main LANL IOR github after which I'll try to get the community
to kill all the other ones out there for both other IOR and other mdtest
because there are a few of them.  And my interest by the way is getting a
single repo to use for the IO500 effort.

On Wed, Jun 7, 2017 at 11:57 AM, Glenn K. Lockwood <notifications@github.com

**Comment by glennklockwood** [comment]
I'm down with that.  I am happy to axe this repository to minimize confusion later on now that APEX bids are in.
